### ISSUE TITLE
Specifying storage_location for local qdrant

### ISSUE THREAD

**Issue by Mohannadcse** [langroid/langroid#181]
**Describe the bug**
There are two issues:
1. `storage_location` can be changed from different perspectives/objects. This can lead to confusion. For example, I can change it from `doc_agent.config.vecdb.storage_path = ".mystorage/data"` or `doc_agent.vecdb.storage_path = ".mystorage/data"`.  However, the latter shouldn't be allowed. While the former leads to the 2nd issue:
2. At this stage, the config of the doc_agent has already been created, which means the qdrant client is already initialized based on the default values (e.g., `storage_path=".qdrant/data/"`). Therefore, the problem here is that when storage_path is changed later on, there is no mechanism to overwrite the `storage_path`. This will lead to inconsistency, because the use assumes the new location, while it hasn't been changed.

**To Reproduce**
Try the above approaches to modify `storage_path` immediately before this [line](https://github.com/langroid/langroid-examples/blob/main/examples/docqa/chat_multi_extract.py#L126), and then debug the code. 

**Expected behavior**
- Changing `storage_path` should be allowed only from one location at the beginning before creating the client

**Comment by pchalasani** [comment]
How about instead -- when `storage_path` is specified anywhere in the code, we recreate the client (whether `chroma` or `qdrant`) ?

**Comment by pchalasani** [comment]
Actually this will lead to the "storage path already used" error I think

**Comment by pchalasani** [comment]
I think we should have a `set_storage_path` method on the `VectorStore` class, and it will do the right checks and prevent re-creation of client if it exists and the `storage_path` has not changed.

**Comment by Mohannadcse** [comment]
Yes, this approach `set_storage_path` will help to avoid the situation above. 
But how this will fix the colab situation? this error `RuntimeError: Storage folder .qdrant/data/ is already accessed by another instance of Qdrant client. If you require concurrent access, use Qdrant server instead.`

**Comment by pchalasani** [comment]
In a notebook with multiple examples, each example will try to create a client anew. We should explicitly set a new storage path for each example, that should solve it?

**Comment by Mohannadcse** [comment]
yes, I was thinking about this, let me try it

**Comment by Mohannadcse** [comment]
> In a notebook with multiple examples, each example will try to create a client anew. We should explicitly set a new storage path for each example, that should solve it?

Just tried this approach, works

**Comment by Mohannadcse** [comment]
Actually, doesn't solve the problem. If the user wants to run the same example again, the same error will show up, even if I change `storage_path`, because the port is still allocated. We need to free the port every time we run the example.

**Comment by Mohannadcse** [comment]
I added this logic before creating any `config` to solve the problem 

```
folder_path = '.data1/data1/'

if os.path.exists(folder_path) and os.path.isdir(folder_path):
    shutil.rmtree(folder_path)
    print(f"The folder '{folder_path}' and all its contents have been removed.")
else:
    print(f"The folder '{folder_path}' does not exist.")
```

**Comment by pchalasani** [comment]
I think it's fine to do this in a colab notebook
